# Site settings
title: SculptorJS
description: "Allows you to easily 'sculpt' beautiful, cross-browser HTML dropdowns with standard CSS"
url: "http://ordergroove.github.com/sculptorjs" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
